adopcion/urls.py
from django.urls import path

from .views import index, SolicitudCreate, solicitud_listar, SolicitudList

app_name = 'adopcion'

urlpatterns = [
    path('', index, name='index'),
    path('solicitud/listar/', SolicitudList.as_view(), name='solicitud_listar'),
    path('solicitud/nueva/', SolicitudCreate.as_view(), name='solicitud_crear'),

]

blog/urls.py
from django.urls import path

from .views import index

urlpatterns = [
    path('', index, name='index')

]

formsLearn/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import logout_then_login

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mascota/', include('mascota.urls')),
    path('adopcion/', include('adopcion.urls')),
    path('blog/', include('blog.urls')),
    path('logout/', logout_then_login, name='logout'),
]

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">

	{% block extrastatic %}
	{% endblock %}

	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<title>{% block title %}Document {% endblock %}</title>
</head>
<body>
<div class="container">

	{% block navbar %}
<nav class="navbar navbar-expand-lg  bg-dark navbar-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>

     <!-- Dropdown -->
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
        Mascotas
      </a>
      <div class="dropdown-menu">
        <a class="dropdown-item" href="{% url 'mascota:mascota_crear' %}">Solicitar</a>
        <a class="dropdown-item" href="{% url 'mascota:mascota_listar' %}">Listar Solicitudes</a>
      </div>
    </li>
    <!-- Dropdown -->
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
        Adopciones
      </a>
      <div class="dropdown-menu">
        <a class="dropdown-item" href="{% url 'adopcion:solicitud_crear' %}">Solicitar</a>
        <a class="dropdown-item" href="{% url 'adopcion:solicitud_listar' %}">Listar Solicitudes</a>
      </div>
    </li>

    </ul>


    <ul class="nav navbar-nav  mt-2 mt-lg-0">
	  <li class="nav-item dropdown">
         <a  class="nav-link" href="http://codigofacilito.com" onclick="pageTracker._link(this.href); return false;">Código Facilito</a>
      </li>

      <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Opciones</a>
            <div class="dropdown-menu">
                <a href="{% url 'logout' %}">Salir</a>
            </div>
       </li>
     </ul>
  </div>
</nav>
	{% endblock %}


	{% block content %}
	<h4>	Bloque de contenido		</h4>
	{% endblock %}


	{% block footer %}
	{% endblock%}
</div>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>

	{% block extrajs %}

      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    {% endblock %}



</body>
</html>

templates/base/header.html
<header>
    <h5>Hola</h5>
</header>